# Site settings
title: Lilypad Career Marketing
description: Your job hunt doesn't have to be this hard! Lilypad Resumes & Lilypad Career Marketing is the top professional resume writing & cover letter writing service for job seekers. Carefully crafted resumes and cover letters that get more interviews.
url: "https://lilypadresumes.com"
logo: /assets/img/logo-light.png
email: gethired@lilypadresumes.com
timezone: America/Winnipeg
google_analytics: UA-96566297-1
repository: chrissavoie/lilypadresumes
github: [metadata]
include: [".htaccess","_pages"]

twitter:
  username: lilypadjobs

social:
  name: Lilypad Career Marketing
  links:
    - https://twitter.com/lilypadjobs
    - https://www.facebook.com/LilyPad-Resumes-1852637254993095/

# URL Vars
urls:
  twitter:      https://twitter.com/lilypadjobs
  facebook:     https://www.facebook.com/LilyPad-Resumes-1852637254993095/

# Collections
collections:
  posts:
    output: true
    permalink: /:title
  samples:
    output: true

# Extras
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-contentblocks

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
